from __future__ import annotations

import locale
import random
import sys
import time
from datetime import datetime

WINDOWS: list[tuple[str, int, int]] = [
    ("dead_of_night", 0, 2),
    ("late_night",    3, 5),
    ("early_morning", 6, 8),
    ("morning",       9, 11),
    ("midday",       12, 13),
    ("afternoon",    14, 16),
    ("evening",      17, 19),
    ("night",        20, 23),
]


def _window_for_hour(hour: int) -> str:
    for wid, start, end in WINDOWS:
        if start <= hour <= end:
            return wid
    return "morning"


# --- Greeting bank -----------------------------------------------------------
#
# Rules for this bank:
#   - Terse, deadpan, senior-dev register. No hype, no pep talk.
#   - Hard char cap: 65. Keep most lines under 60.
#   - No exact clock hours. Each window spans 2–4 hours; sentences must
#     read true anywhere in it. Use fuzzy markers ("past midnight",
#     "this late", "pre-standup", "after hours") instead.
#   - The terminal, compiler, and AI are characters. They don't judge.
#   - Ironic juxtaposition over jokes. Observation over cheerleading.
#
GREETINGS: dict[str, list[tuple[str, str]]] = {
    "dead_of_night": [
        ("🌑", "Past midnight. Technically a new day, spiritually the same one."),
        ("⏰", "The day is over. The question is which day."),
        ("📜", "The git log ends here. For now."),
        ("🤔", "Midnight is when senior devs briefly become philosophers."),
        ("🐛", "Almost tomorrow. The bugs will still be waiting."),
        ("🤖", "The compiler has no opinion on your life choices."),
        ("🚀", "Last push of the day, technically speaking."),
        ("📅", "The deadline is either tomorrow or past."),
        ("🧪", "Deep in the night, everything is a commitment to a theory."),
        ("💻", "Still open, still running. That counts for something."),
        ("🌃", "The city sleeps. The terminal does not."),
        ("📝", "Tomorrow's PR starts now. Apparently."),
        ("🕯️",  "The witching hour, but for segfaults."),
        ("🫠", "Your sleep schedule is now a suggestion."),
        ("📊", "Velocity: undefined. Hour: hostile."),
        ("🌙", "The moon has notes on your architecture."),
        ("🧠", "Late enough that the TODOs look like prophecies."),
        ("☕", "Coffee at this hour is a hostile act against morning."),
        ("⌨️",  "The keyboard is warm. The judgment is cold."),
        ("🔇", "Quiet hours. The only noise is the fan."),
        ("📁", "You have been in this file for hours. Say hi."),
        ("🪦", "Here lies today's plan. Survived by one branch."),
        ("🔒", "Everyone else logged off. You forgot."),
        ("🫥", "On call, but only for yourself."),
        ("🪞", "The screen glow is your only co-worker now."),
        ("🎭", "You are both dev and user now. Both are tired."),
        ("📎", "Linting at this hour feels personal."),
        ("🪤", "One more log line and you are free. Probably."),
        ("🪄", "The fix is one character. Always one character."),
        ("🧷", "Holding it together with a git stash."),
        ("🌌", "The context window is vast. So is the night."),
        ("🧯", "Something is on fire. Probably not urgent."),
        ("🗺️",  "The repo is a country. You are lost in it."),
        ("🔋", "Battery at 20%. So is resolve."),
        ("🎢", "The diff goes up. The confidence goes down."),
        ("🔦", "Debugging by vibe now. Officially."),
        ("🪫", "Low power. Low standards. Still shipping."),
        ("🌡️",  "The laptop is warmer than the room."),
        ("🪟", "The only window with lights. Yours."),
        ("📮", "Queued for morning. Probably."),
        ("📼", "Replaying the same stack trace. Subtitles off."),
        ("💤", "Sleep was a feature flag. It is off."),
        ("🎯", "Precision at this hour is a lie we like."),
        ("🔌", "Plugged in. Committed in both senses."),
        ("🧾", "The receipt for today will arrive tomorrow."),
        ("🗿", "Staring at the monitor. Both of you stoic."),
        ("🛸", "No one is coming to ship this for you."),
        ("🎙️",  "The inner monologue has become narration."),
        ("🔭", "Looking for the bug. Finding the hour."),
        ("🧿", "This run will be the one. Like the last four."),
    ],
    "late_night": [
        ("❌", "The tests are failing. The night is long."),
        ("😴", "CI is asleep. You should be too."),
        ("⚠️",  "Nothing good was ever merged at this hour."),
        ("📝", "The diff is long. The night is longer."),
        ("😬", "Your future self will not thank you for this."),
        ("👁️",  "Insomnia or deadline — the terminal does not judge."),
        ("🌀", "This is not a phase. Or maybe it is."),
        ("🔴", "The log errors make more sense than the hour."),
        ("💪", "Past a certain hour, stubbornness becomes personality."),
        ("⌛", "The cursor blinks patiently. You have not."),
        ("🧱", "The wall is the same. Your shoulder is tired."),
        ("🦉", "Technically still productive. Technically."),
        ("🧠", "The ideas get worse. The confidence grows. A trap."),
        ("🧰", "Every tool looks like a hammer at this hour."),
        ("🪞", "The rubber duck walked out. It had boundaries."),
        ("📉", "Code quality at this hour follows one law: entropy."),
        ("🫠", "You are no longer debugging. You are coexisting."),
        ("🔧", "Every fix now creates exactly two more."),
        ("🧭", "Lost the thread hours ago. Still pulling on something."),
        ("🎯", "The target keeps moving. You keep aiming."),
        ("🛌", "The bed exists. It is a verified resource."),
        ("📚", "The docs would help. You will not read them."),
        ("🗡️",  "One more fix and it is done. Like before."),
        ("🐉", "The dragon in main is your dragon now."),
        ("🪫", "Low battery, high commitment. A poor combination."),
        ("🫥", "You stopped narrating. That is usually a sign."),
        ("🧪", "Running the same command with different feelings."),
        ("🎭", "You are method-acting a productive person."),
        ("🕳️",  "The bug is here. The bug is somewhere. The bug is you."),
        ("🫧", "The logic was clear two hours ago. It is not."),
        ("🫀", "The heart of the bug is still beating."),
        ("🌡️",  "Running hot. Both the code and the operator."),
        ("🪤", "The edge case that lured you in is still here."),
        ("🗺️",  "Somewhere in this repo is the answer. Not near you."),
        ("🧯", "Nothing is on fire. Nothing is fine either."),
        ("🪛", "Tightening screws on a machine that left the station."),
        ("🎲", "Refreshing the logs like they will say something new."),
        ("📟", "Pinging oneself for ideas. Silence."),
        ("🫣", "Tomorrow's code review will see this. No."),
        ("🪜", "One rung at a time. Mostly the same rung."),
        ("🌫️", "The code is foggy. Your reasoning is foggier."),
        ("🪃", "Every fix comes back to hit you. Expected."),
        ("🪐", "This orbit is long. The bug is dense."),
        ("🎧", "The playlist is a friend. Also a crutch."),
        ("🏚️", "Something was elegant here once. Hours ago."),
        ("🔗", "Chaining fixes like they were meant to meet."),
        ("💡", "A new idea. It is probably the old idea."),
        ("🎤", "Describing the bug out loud. To the kettle."),
        ("🗝️",  "The key is somewhere. You have opened everything else."),
        ("🧩", "Working memory has left. Muscle memory remains."),
    ],
    "early_morning": [
        ("⚡", "Either very early or very late. Bold either way."),
        ("☕", "The coffee has not lied to you yet today."),
        ("🐦", "Some birds are up. You have that in common."),
        ("📄", "Dawn and a blank editor — similarly unforgiving."),
        ("🤫", "Still dark. Your standup will never know."),
        ("✅", "First commit of the day. The record is clean."),
        ("🌍", "The world boots slowly. Give it a moment."),
        ("🌅", "Up before the sun. The sun does not care."),
        ("📋", "Pre-standup: the last hour the plan still exists."),
        ("⌨️",  "The keyboard is already warm. The day has not started."),
        ("🌄", "The light is theoretical. The coffee is not."),
        ("🫖", "The kettle agrees with everything this early."),
        ("📬", "Inbox untouched. This is peak career."),
        ("🧘", "Nobody needs anything yet. Savor it."),
        ("🐣", "A soft boot. Both you and the machine."),
        ("🧊", "The laptop is cold. The ambition is colder."),
        ("🌁", "Fog outside. Clarity somewhere inside. Allegedly."),
        ("🪞", "The terminal is the most honest mirror you have."),
        ("📆", "The calendar is empty. That will change violently."),
        ("🛎️",  "No notifications. That is its own anomaly."),
        ("🧽", "A clean slate. Do not scribble on it yet."),
        ("🪴", "Nothing is broken. You have not opened the repo."),
        ("🗞️",  "The incident report can wait. Nobody has filed it."),
        ("🐦‍⬛", "The commit history is quiet. Good."),
        ("🌤️", "Slight sun. Slight will to live. Enough."),
        ("🧪", "Running pre-standup hypotheses. None verified yet."),
        ("🎚️",  "Volume low. Focus pending."),
        ("🔑", "You remember the password. That is a good sign."),
        ("🧑‍🚀", "Solo mission until standup. Enjoy the orbit."),
        ("🧱", "The blocker from last night is still there. Wait."),
        ("🛫", "The day has not taken off. You are at the gate."),
        ("📖", "Reading your own comments. They need work."),
        ("🧭", "The morning has a plan. It is already loose."),
        ("🚿", "You've already had the shower thoughts."),
        ("🔔", "The alarm worked. Everyone is surprised."),
        ("📤", "An unsent email is a gift to your future self."),
        ("🪟", "The blinds are up. So are you. Barely."),
        ("🔮", "Today's problems have not made themselves known."),
        ("☀️",  "Light is a hint, not a commitment."),
        ("🧗", "Pulling up to the keyboard like it's a ledge."),
        ("🪵", "A slow start. Split the wood in small pieces."),
        ("🧨", "Not yet. Don't light anything yet."),
        ("🐓", "The rooster of CI has not crowed yet."),
        ("🕰️",  "The day is young and unconvinced."),
        ("📏", "Measure twice. You are not awake enough to cut."),
        ("🦢", "Everything looks graceful before the first bug."),
        ("🎼", "Tuning up. The concert is later."),
        ("🪔", "A small light. Enough to type by."),
        ("📭", "Mail is light. Meetings are next. Brace."),
        ("🧩", "The day is a puzzle. Most pieces face down."),
    ],
    "morning": [
        ("📌", "The workday technically exists now. Noted."),
        ("☕", "Still two cups of coffee from being functional."),
        ("📆", "Your calendar has opinions. Ignore some of them."),
        ("🐛", "Morning. The bugs from last night are still there."),
        ("🔄", "Fresh session. The context is already loading."),
        ("✅", "Reasonable hour. Low bar, but you cleared it."),
        ("🏃", "The day is young. You are not. Go anyway."),
        ("📬", "Inbox zero is a myth. This session is real."),
        ("🎤", "Standup: rehearsed, misheard, forgotten."),
        ("🕰️",  "The morning has opinions about itself."),
        ("📊", "Sprint board updates itself only in dreams."),
        ("🧠", "Working memory: partial. Ambition: full."),
        ("🔔", "The first notification arrives. The day is real."),
        ("🧰", "The tools are sharp. The plan is not."),
        ("🗓️",  "Three meetings survived the calendar purge."),
        ("🪟", "Good light. Better excuses for not shipping yet."),
        ("💼", "Slack is warm. Your coffee is warmer. For now."),
        ("🧭", "Direction: unclear. Pace: optimistic."),
        ("🎯", "The first task is a small one. Build momentum."),
        ("🚦", "Green CI is a morning miracle. Do not dwell."),
        ("📖", "Reading yesterday's code like a stranger's."),
        ("🪞", "The PR from Friday is watching you."),
        ("🧱", "The blocker is still a blocker. Good morning."),
        ("🎛️",  "Adjusting the scope before it adjusts you."),
        ("🧘", "Breathing exercises, known as reading Slack."),
        ("🏗️", "Foundations first. Features after lunch. Maybe."),
        ("📈", "A small win before noon keeps the afternoon honest."),
        ("🪴", "Someone emailed at 5am. It can wait."),
        ("🗞️",  "Oncall did not page you. Treasure this."),
        ("🧑‍💻", "The IDE is open. That is half the battle."),
        ("🪄", "You remember the codebase. Confidence is premature."),
        ("🧮", "Estimates are fiction. Read yours with fondness."),
        ("📮", "An unopened PR request. The day has texture now."),
        ("🫖", "The tea in the cup is today's only true schedule."),
        ("🧯", "An alert was a false alarm. Like the last four."),
        ("🧳", "Yesterday's context is back. Put it on slowly."),
        ("🌤️", "Mild weather. Mild optimism. Enough."),
        ("🔍", "Reviewing the PR you wrote at midnight. Brave."),
        ("🛋️",  "Remote work: the cat has thoughts on your architecture."),
        ("🔧", "A small chore to warm up. It will take an hour."),
        ("📑", "Docs exist. You have heard legends."),
        ("📦", "Dependencies updated overnight. Hopefully nothing broke."),
        ("🪛", "Minor fix to warm up. The classic trap."),
        ("📠", "The ticket is open. It stays open until proven otherwise."),
        ("🎬", "The morning has scenes. The big scene is later."),
        ("🎨", "The UI ticket looks easy. It never is."),
        ("🧩", "Puzzle pieces on the desk. None upside-right."),
        ("🥁", "The standup drum. Brief. Survivable."),
        ("📍", "You know where you left off. That is the win."),
        ("🥂", "The build passed on main. Tiny celebration."),
    ],
    "midday": [
        ("😅", "Noon. The morning got away from you again."),
        ("💡", "Pre-lunch clarity: use it before it evaporates."),
        ("🤖", "Lunch is a suggestion. The compiler has a deadline."),
        ("📊", "The sprint board has not moved itself. Interesting."),
        ("😊", "Midday: peak optimism about the afternoon."),
        ("⚖️",  "Halfway through the workday, or halfway into it."),
        ("🎬", "The morning was a rehearsal. This is the actual work."),
        ("🧠", "Late enough to have context, early enough to use it."),
        ("⏱️",  "The afternoon exists, for better or worse."),
        ("💥", "Midday: the hour the plan meets reality."),
        ("🍽️",  "Lunch is negotiable. The stack trace is not."),
        ("📌", "Pin one thing before lunch. Just one."),
        ("🌞", "The sun is loud. Your focus is quiet."),
        ("🧭", "The compass reads: after lunch. Proceed cautiously."),
        ("🕰️",  "Time has taken a shape. It is a brick."),
        ("🪟", "Outside is lovely. Inside is the PR queue."),
        ("🫕", "Everything on your plate. Literally and not."),
        ("🧘", "A breath between meetings. If lucky."),
        ("📝", "Half the TODO list is now someone else's problem."),
        ("🪞", "Check the plan. Adjust the plan. Lose the plan."),
        ("🎯", "Aim small at midday. Miss small."),
        ("🧋", "The second coffee is not a second chance. It is a lie."),
        ("🧮", "Half the day remains. A generous interpretation."),
        ("📆", "The calendar has more meetings than ideas."),
        ("🔔", "Notifications now come in clusters. Triage them."),
        ("🧱", "The blocker broke. Time for the next blocker."),
        ("🧤", "Handle the midday ticket with care. It bites."),
        ("🗓️",  "The afternoon calendar reads: busy and vague."),
        ("📉", "Energy: dipping. Plans: intact. For now."),
        ("🧳", "Lunch packed with yesterday's leftovers, like context."),
        ("🌬️", "Open a window. Close two tabs. Begin again."),
        ("💾", "Working memory is expensive. Checkpoint before lunch."),
        ("🥡", "Leftovers are a branch. Close them by next week."),
        ("🔍", "Peek at the PR. Do not open it unless ready."),
        ("📬", "The inbox has opinions. Most are wrong."),
        ("🫠", "The standup ideas, melting in the sun."),
        ("🧯", "Not a fire. A small, warm, ongoing problem."),
        ("📻", "Radio silence on Slack. Suspicious."),
        ("🎤", "The afternoon sync: prepare to repeat yourself."),
        ("📡", "Signals from the PM. Acknowledge. Translate."),
        ("🛎️",  "A stakeholder pings. The focus bell rings."),
        ("🕳️",  "One meeting away from a deep hole. Avoid if possible."),
        ("🧩", "Pieces fit together, reluctantly."),
        ("🏁", "Ship one thing before lunch. A small thing counts."),
        ("🪑", "The chair has been warm too long. Stand."),
        ("🎞️",  "Rolling into the afternoon. Mark the take."),
        ("🪙", "Flip a coin for the feature or fix. Usually fix."),
        ("📍", "You are here. It is not where you hoped."),
        ("📏", "Measure progress now. It will lie again by 3."),
        ("🔧", "Tighten what you ship. Loosen what you plan."),
    ],
    "afternoon": [
        ("🌫️", "Post-lunch. Your stack trace is not the only thing foggy."),
        ("📡", "Peak meeting time, minimum information exchanged."),
        ("📝", "The afternoon is long. So is your TODO list."),
        ("🔭", "Halfway through the day. The code has not noticed."),
        ("🔬", "The feature exists in theory. The afternoon will find out."),
        ("📈", "Statistically the least productive hours. Prove it wrong."),
        ("😬", "Afternoon: when confident commits become cautious ones."),
        ("🦆", "Somewhere a rubber duck is solving someone's problem."),
        ("☕", "The caffeine wore off. So did the plan."),
        ("⏰", "The last honest hour of the workday."),
        ("🪟", "The light is slanting. Deadlines are straightening."),
        ("🧘", "Between meetings: a small, doomed silence."),
        ("🎯", "Aiming at Friday. Hitting Wednesday."),
        ("📊", "The burndown chart is flat. Like your expression."),
        ("🫠", "The stand-up clarity, officially gone."),
        ("🪞", "The PR thread has seven comments. None are joyful."),
        ("🎤", "The retro is in your mind already. It is not kind."),
        ("📦", "Shipping mode or stashing mode. Pick one this hour."),
        ("🪜", "Climbing up to a minor feature. The ladder is wobbly."),
        ("📏", "Measure twice. Deploy once. Regret slightly."),
        ("🧪", "Running the test suite for comfort now. Like incense."),
        ("🧭", "The original plan was a nice plan. Noted."),
        ("🧱", "The blocker is back. Different sweater."),
        ("🧲", "Drawn to the one ticket you have been avoiding."),
        ("🪣", "Pouring effort into a bucket. It has a small hole."),
        ("🎬", "Take two. The morning was takes one through four."),
        ("🧯", "Afternoon fires are smaller. They still smoke."),
        ("🧠", "Cognitive load: nominal. Motivation: modest."),
        ("🎚️",  "The focus has left the room. Expected."),
        ("📮", "The ticket you closed yesterday was reopened."),
        ("🗓️",  "Tomorrow's meetings are creeping into today."),
        ("🔁", "Reloading the same page hoping for new content."),
        ("🪝", "The hook of a long meeting. Don't bite hard."),
        ("📉", "Productivity dips. The coffee machine knows."),
        ("🎛️",  "Balancing scope, calendar, and the urge to nap."),
        ("🧺", "Folding tickets: done, doing, doomed."),
        ("🪴", "The plant on the desk has more focus than you."),
        ("🪛", "Small fix, heavy weight. The afternoon special."),
        ("🔎", "Searching for a lost import. Finding a lost hour."),
        ("🫣", "The PR you avoided is now the PR you open."),
        ("🗯️", "Second-guessing morning decisions is an afternoon sport."),
        ("🎲", "Rolling for a clean CI run. Natural one."),
        ("🧩", "The puzzle has four edges. They do not meet."),
        ("🛎️",  "The PM pings. The focus resets. You endure."),
        ("🧤", "Handle the migration carefully. It has a temper."),
        ("📍", "You are here. The afternoon is unimpressed."),
        ("🔮", "Predicting Friday from here is reckless."),
        ("🎨", "The UI looks fine. The UX is a separate argument."),
        ("🧰", "Tools laid out. The will is elsewhere."),
        ("🪢", "Untangling three tickets that should have been one."),
    ],
    "evening": [
        ("🌙", "After hours. The definition of that is flexible for you."),
        ("📉", "The day had a shape. This is the trailing edge."),
        ("🚢", "Ship it or stash it — the evening asks that question."),
        ("⌚", "Technically off the clock. The terminal missed that memo."),
        ("🍽️",  "Dinner is a concept. So is done."),
        ("🔁", "Evening: the hour of one-more-thing."),
        ("✅", "The build passed. You can probably stop now. Probably."),
        ("📖", "Whatever did not ship today is tomorrow's character arc."),
        ("❓", "After hours, the codebase has questions."),
        ("🎯", "The line between work and a hobby blurs."),
        ("🌆", "The light is gone. The branch is still open."),
        ("🪑", "The chair is still warm. The desk is still honest."),
        ("🪞", "The stand-up summary was optimistic. This hour corrects."),
        ("🍷", "Dinner plans exist. The cursor is patient. Both win."),
        ("📦", "Packaging up the day. Most of it fits."),
        ("🧺", "Loose ends, carefully coiled for tomorrow."),
        ("📮", "The last email of the day writes itself differently."),
        ("🪟", "Lights on in half the apartments. Yours too."),
        ("🧯", "Nothing urgent. Everything cumulative."),
        ("🧮", "Counting the small wins. Finding more than expected."),
        ("🎬", "Rolling credits on today. Bloopers on main."),
        ("🧊", "Cooling down. The laptop fan disagrees."),
        ("📑", "Documenting what happened for future-you."),
        ("🧭", "The day's compass reads: wrap up. Listen."),
        ("🧠", "A second wind exists. Do not trust it."),
        ("🎛️",  "Dimming the focus. Slowly. Unconvincingly."),
        ("📱", "Your phone starts to win attention. Predictable."),
        ("🪙", "Ship today, fix tomorrow. A classic evening coin."),
        ("🗓️",  "Tomorrow has fewer meetings. A tiny gift."),
        ("🛎️",  "One last Slack ping. Respond briefly. Resist."),
        ("🧷", "Pinning the work at a safe checkpoint."),
        ("🎤", "The retro note of the day: ship small, sleep early."),
        ("📡", "Signals quiet. PMs dispersing. Breath available."),
        ("📊", "The day's diff, summed: non-zero. Acceptable."),
        ("🏁", "A small, neat push. Then stop. Please stop."),
        ("🪛", "Last small fix. It always spawns one more."),
        ("🪜", "Coming down the ladder. Slowly. One foot at a time."),
        ("🗝️",  "Locking up the day. Keys for tomorrow."),
        ("🔒", "Log off is a verb. Mostly aspirational."),
        ("🫠", "The motivation, pooling at the bottom of the day."),
        ("🪫", "Low battery. Healthy boundary, if honored."),
        ("🕯️",  "One small light on the desk. That is enough."),
        ("📝", "Tomorrow's TODO list, written with honesty."),
        ("🧳", "Packing context into the commit. Clearly, for once."),
        ("🎨", "The polish pass always eats the evening. Always."),
        ("📪", "Inbox winding down. A rare and soft relief."),
        ("🔔", "Oncall is not you tonight. Savor it."),
        ("🍝", "Dinner is late because the tests were first."),
        ("📍", "You are further than you thought. Closer than you feel."),
        ("🕰️",  "Off hours: when the codebase finally relaxes."),
    ],
    "night": [
        ("🤡", "A reasonable time to start a refactor. Said no one."),
        ("📉", "The diff grows. The rationale shrinks."),
        ("🖱️",  "Dark outside. The cursor blinks, unbothered."),
        ("💬", "Late enough that the commit message will be honest."),
        ("🔥", "You and the code, alone again. This is fine."),
        ("🎯", "This late: ambitious scope, poor estimates."),
        ("⌨️",  "The keyboard has been patient with you all day."),
        ("🤷", "Not the last session of the week. Probably not."),
        ("🔮", "The feature is close. It has always been close."),
        ("🌃", "The night shift begins, asked for or not."),
        ("🪞", "The code you wrote at 9am disagrees with you now."),
        ("🪟", "Dark windows everywhere. Yours is glowing. Suspicious."),
        ("🕯️",  "A single tab is lit. You are inside it."),
        ("🔇", "Slack is quiet. The repo is loud."),
        ("🧠", "Past the caffeine peak. Into improvisation."),
        ("📡", "Signals to the rest of the world: muted."),
        ("🪫", "Low battery. High conviction. Classic combo."),
        ("🧘", "The evening's calm has curdled into stubbornness."),
        ("🫠", "The plan has softened. Your typing has not."),
        ("📜", "Writing the commit message like a letter."),
        ("🧪", "Tests, again. Always tests, again."),
        ("🧯", "The last fire of the day is small but hot."),
        ("🛏️",  "Bed was a feature request. You deprecated it."),
        ("🎧", "Music is holding the project together. Thank it."),
        ("🧹", "Sweeping the diff clean. One more pass. Maybe two."),
        ("🧵", "The thread of the fix is long. You are still holding it."),
        ("🪜", "Climbing out of a yak stack. Slowly."),
        ("🗺️",  "Somewhere in this module is the answer. Keep walking."),
        ("📦", "Shipping decision: tomorrow. Sign it and mean it."),
        ("🔧", "Every screw tightened is a screw to re-check tomorrow."),
        ("🪛", "Another small fix. That is how the night progresses."),
        ("🧱", "The wall moved. You moved with it. Even trade."),
        ("🧭", "The north star is sleep. You are heading east."),
        ("🪐", "The repo has gravity at this hour. Escape velocity is low."),
        ("🧙", "Debugging by memory, not by reading. Risky."),
        ("🦉", "Wiser than the PR you opened this morning. Barely."),
        ("🧰", "The tools are dull. Sharpness is tomorrow's problem."),
        ("🕳️",  "You have found the rabbit hole. It is comfortable."),
        ("📻", "The hum of the fan is the song of the night."),
        ("📚", "Reading the diff like it is a thriller. It is not."),
        ("🪴", "The plant judges you. In plant time."),
        ("🎨", "The polish you added at noon is now questionable."),
        ("🫥", "Halfway between working and just being online."),
        ("🧷", "Pinning the branch at a safe commit. Mostly safe."),
        ("📮", "Tomorrow's email is writing itself, resentfully."),
        ("🫕", "The codebase is fondue again. So are your thoughts."),
        ("🎤", "Narrating the fix to the empty room. Helpful."),
        ("🔒", "Locking it in. Almost. One more log statement."),
        ("🌙", "The moon has seen worse commits."),
        ("🧲", "One more ticket pulls you back. Let it."),
    ],
}

# --- Goodbye bank ------------------------------------------------------------
#
# Printed to stderr after a session ends. Same voice rules as greetings.
# Public name — imported by altergo.py.
#
GOODBYES: list[tuple[str, str]] = [
    ("👋", "Back to reality. Good luck with the next bug."),
    ("🚪", "Session closed. The context window has left the building."),
    ("🤔", "That was productive, ah?"),
    ("💬", "The chat is over. Your git blame remains."),
    ("🧠", "All that intelligence, and it still couldn't push to main for you."),
    ("⏱️",  "See you in 5 minutes when the next edge case appears."),
    ("🔮", "The model has spoken. Whether it was right is your problem."),
    ("💸", "Tokens spent. Wisdom optional."),
    ("📝", "Another session closed. Another PR description that writes itself."),
    ("🤷", "Done. The AI did the thinking. You take the blame."),
    ("✅", "Clean exit. The work continues."),
    ("🍀", "Until next time. May your tests be green."),
    ("📌", "Context preserved. You know where to find it."),
    ("🚀", "Ship it."),
    ("💾", "Commit early, commit often. You know the drill."),
    ("🧭", "Back to the real repo. The one you own."),
    ("🪞", "The cursor is yours again. Use it wisely."),
    ("🎬", "Scene ends. The bugs carry on."),
    ("🔇", "The assistant is muted. The compiler is not."),
    ("🛫", "Handing back the controls. Try not to stall."),
    ("🎯", "Close enough to done. The rest is a commit away."),
    ("🫡", "Dismissed. The branch salutes you."),
    ("📡", "Signing off. The repo is listening."),
    ("🪛", "Tool down. The screw is mostly in."),
    ("🗝️",  "Unlocked one thing. The lock upgraded itself."),
    ("🧯", "Fire handled. Smoke alarms, not our department."),
    ("📤", "Handoff complete. The next session knows nothing."),
    ("🪄", "Magic faded. The diff remains."),
    ("🧵", "Thread closed. The yak stack is half-shaved."),
    ("🔁", "Loop exited. Or paused. Same thing, sometimes."),
    ("📖", "Chapter done. Tomorrow writes itself."),
    ("🧩", "Piece placed. The puzzle gained three new edges."),
    ("🛌", "The AI naps. You should too. In theory."),
    ("🧘", "Exhale. Then open the PR."),
    ("🧑‍🚀", "Re-entry. Brace for your calendar."),
    ("🔒", "Session locked. Take the key."),
    ("🧳", "Context packed. The PR description is half-drafted."),
    ("🪤", "Out of the rabbit hole. For now."),
    ("🗂️",  "Filed. The label is 'probably correct'."),
    ("🧱", "Blocker cleared. Next blocker loading."),
    ("🔎", "Search ended. Found some of the thing."),
    ("🦆", "The rubber duck takes it from here."),
    ("🪙", "Flipped. Heads shipped. Tails stashed. Either way, out."),
    ("🧑‍💻", "Back to manual piloting. Seatbelt on."),
    ("🔕", "Notifications your problem again. Good luck."),
    ("🪫", "Model ran warm. Your turn to idle."),
    ("🧪", "Experiment ended. The hypothesis lives on."),
    ("🫣", "Out before the PR review, like a professional."),
    ("🏁", "Flag drops. The loop waves back."),
    ("🔌", "Unplugged. The repo will survive the silence."),
]


NATURE_ICONS: list[str] = ["🌊", "🌿", "⛰️", "🌳", "🔥", "🌄", "🌑"]
NATURE_ICONS_ASCII: list[str] = ["~", '"', "^", ":", "*", "/", "o"]


def _supports_unicode() -> bool:
    enc = (getattr(sys.stdout, "encoding", None) or "").lower()
    if enc.startswith(("utf", "cp65001")):
        return True
    try:
        loc = (locale.getpreferredencoding(False) or "").lower()
    except Exception:
        loc = ""
    return loc.startswith("utf")


def pick_icon(now: datetime | None = None) -> str:
    when = now or datetime.now()
    idx = when.weekday()
    if _supports_unicode():
        return NATURE_ICONS[idx]
    return NATURE_ICONS_ASCII[idx]


def pick_greeting(now: datetime | None = None) -> tuple[str, str]:
    """Return ``(emoji, text)`` for the current time window."""
    when = now or datetime.now()
    window = _window_for_hour(when.hour)
    bank = GREETINGS.get(window) or GREETINGS["morning"]
    seed = int(time.time() // 60)
    rng = random.Random(seed ^ hash(window))
    return rng.choice(bank)


def pick_goodbye() -> tuple[str, str]:
    """Return ``(emoji, text)`` for the end-of-session handoff line."""
    return random.choice(GOODBYES)


THEME_SPINNERS: dict[str, str] = {
    "ocean":    "star",
    "forest":   "star",
    "lavender": "star",
    "sunset":   "star",
    "mono":     "star2",
    "rainbow":  "star",
}


def spinner_for_theme(theme_id: str) -> str:
    return THEME_SPINNERS.get(theme_id, "dots")
